#!/bin/bash
for beam_energy in 0.9 2 5 10 18; do
    for theta in 178 178.73; do 

    # Input simulation parameters
    particle="e-"
    #beam_energy=18
    num_events=500
    theta_min=$theta # in degrees
    theta_max=$theta # in degrees
    phi_min=90. # in degrees
    phi_max=270. # in degrees 
    physics_list="FTFP_BERT"

    theta="${theta_min}-${theta_max}"

    # Output file names
    info_string="${particle}_${beam_energy}GeV_theta_${theta}deg"
    hepmcfile="gen_${info_string}.hepmc"
    simfile="insert_sim_${info_string}.edm4hep.root"
    recofile="insert_reco_${info_string}.edm4hep.root"
    
    # Generating hepmc file
    root -l -b -q "./hepmc_generation/gen_particles.cxx+(\
${num_events},\
\"${hepmcfile}\",\
\"${particle}\",\
${theta_min},\
${theta_max},\
${phi_min},\
${phi_max},\
${beam_energy})"

    # Running simulation
    npsim \
   --compactFile backwards_insert_with_beampipe_and_flange.xml \
   --numberOfEvents ${num_events} \
   --physicsList ${physics_list} \
   --inputFiles ${hepmcfile} \
   --outputFile ${simfile}  || exit
   
    # Deleting hepmcfile  
    rm ${hepmcfile}

    # Running reconstruction
    export JUGGLER_SIM_FILE=${simfile} JUGGLER_REC_FILE=${recofile} JUGGLER_N_EVENTS=${num_events}
    gaudirun.py backwards_insert_reco.py
done
done
